server:
  port: 9080
spring:
  redis:
    host: redis
  datasource:
    url: jdbc:mysql://localhost/order_service_db
    username: root
    password: abcd1234
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://dmall-order-db.cti1pnc10c3g.rds.cn-north-1.amazonaws.com.cn/order_service_db
    username: admin